### ISSUE TITLE
24 hour time format

### ISSUE THREAD

**Issue by csadam** [jhuckaby/Cronicle#250] opened 2020-01-13 13:50 UTC
Is it possible to display time values in 24 hour format instead of AM/PM?

**Comment by jhuckaby** [comment] 2020-01-18 03:10
Not currently, but I would be happy to add this feature.

**Comment by ugoviti** [comment] 2022-12-24 17:25
Hi, definitively a useful feature.

Thankyou!

**Comment by Zixim** [comment] 2023-07-03 12:05
definately +1

**Comment by Shto1337** [comment] 2024-09-10 16:10
+1

**Comment by ugoviti** [comment] 2024-09-11 07:30
+1 absolutely for me too :)

**Comment by Richdark** [comment] 2024-09-27 16:14
Hey, I've just started using Cronicle and it has been amazing so far! The lack of option to switch to 24-hour format is really the only thing that is bothering me at the moment, so one more vote for this from me. Anyway, thank you for this project!

**Comment by jhuckaby** [comment] 2024-09-27 17:01
So sorry for the delay on this.  It is coming in v2!  Due for release in early 2025.

See #99 for a screenshot.

Closing this as it's actually a duplicate of #99

**Closed by jhuckaby** 2024-09-27 17:01 UTC
Labels: enhancement
