### ISSUE TITLE
[Feature] User Auth - LDAP Support

### ISSUE THREAD

**Issue by fullmoon4465** [jhuckaby/Cronicle#237] opened 2019-11-04 17:01 UTC
Having the option to do ldap auth would be a nice to have. I know theres npm modules that support this somewhere as I use it in NodeRed for auth.

What I'm thinking of is the basic config for ldap auth (user/pass) host/port/bind creds. I would be perfectly fine having to add the users in the UI still manually and assign permissions there. Version 2.0 could have the ability to assign group filters etc.. for permissions etc...

**Comment by jhuckaby** [comment] 2019-11-04 17:22
Duplicate of https://github.com/jhuckaby/Cronicle/issues/16

**Closed by jhuckaby** 2019-11-04 17:22 UTC
