### ISSUE TITLE
After upgrading 0.8.48 to 0.8.49, Copy Event gives 500

### ISSUE THREAD

**Issue by Taz4Git** [jhuckaby/Cronicle#333] opened 2020-10-08 16:42 UTC
## Summary

If we copy an event, the cronicle service will crash.

## Steps to reproduce the problem

- Edit an event
- Click Copy Event
- Click Create Event

Then a message will appear:
Network Error: 500: An unknown network error occured. Please try again.
Nothing works until we restart the cronicle service.

### Operating system and version?

Ubuntu 20.04.1 LTS

### Node.js version?

v12.19.0

### Cronicle software version?

0.8.49

### Are you using a multi-server setup, or just a single server?
single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
filesystem

### Can you reproduce the crash consistently?
Yes

## Log Excerpts

**/opt/cronicle/logs/Error.log**

[1602168417.865][2020-10-08 16:46:57][Server082][2193126][Error][error][crash][Emergency Shutdown: TypeError: Cannot read property 'toString' of null][]
[1602169190.88][2020-10-08 16:59:50][Server082][2500886][Error][error][crash][Emergency Shutdown: TypeError: Cannot read property 'toString' of null][]
[1602170781.575][2020-10-08 17:26:21][Server082][698][Error][error][crash][Emergency Shutdown: TypeError: Cannot read property 'toString' of null][]

**/opt/cronicle/logs/crash.log**

Thu Oct 08 2020 16:46:57 GMT+0200 (Central European Summer Time) - Server082 - PID 2193126
TypeError: Cannot read property 'toString' of null
    at constructor.requireParams (/opt/cronicle/node_modules/pixl-server-user/user.js:1298:21)
    at constructor.requireParams (/opt/cronicle/lib/api.js:474:23)
    at constructor.api_create_event (/opt/cronicle/lib/api/event.js:84:13)
    at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)
    at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:1108:12)
    at /opt/cronicle/node_modules/pixl-server-web/web_server.js:1041:10
    at /opt/cronicle/node_modules/async/dist/async.js:473:16
    at replenish (/opt/cronicle/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)
    at /opt/cronicle/node_modules/async/dist/async.js:958:16

Thu Oct 08 2020 16:59:50 GMT+0200 (Central European Summer Time) - Server082 - PID 2500886
TypeError: Cannot read property 'toString' of null
    at constructor.requireParams (/opt/cronicle/node_modules/pixl-server-user/user.js:1298:21)
    at constructor.requireParams (/opt/cronicle/lib/api.js:474:23)
    at constructor.api_create_event (/opt/cronicle/lib/api/event.js:84:13)
    at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)
    at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:1108:12)
    at /opt/cronicle/node_modules/pixl-server-web/web_server.js:1041:10
    at /opt/cronicle/node_modules/async/dist/async.js:473:16
    at replenish (/opt/cronicle/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)
    at /opt/cronicle/node_modules/async/dist/async.js:958:16

Thu Oct 08 2020 17:26:21 GMT+0200 (Central European Summer Time) - Server082 - PID 698
TypeError: Cannot read property 'toString' of null
    at constructor.requireParams (/opt/cronicle/node_modules/pixl-server-user/user.js:1298:21)
    at constructor.requireParams (/opt/cronicle/lib/api.js:474:23)
    at constructor.api_create_event (/opt/cronicle/lib/api/event.js:84:13)
    at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)
    at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:1108:12)
    at /opt/cronicle/node_modules/pixl-server-web/web_server.js:1041:10
    at /opt/cronicle/node_modules/async/dist/async.js:473:16
    at replenish (/opt/cronicle/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)
    at /opt/cronicle/node_modules/async/dist/async.js:958:16

**/opt/cronicle/logs/Cronicle.log**

[1602168417.865][2020-10-08 16:46:57][Server082][2193126][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'toString' of null][TypeError: Cannot read property 'toString' of null     at constructor.requireParams (/opt/cronicle/node_modules/pixl-server-user/user.js:1298:21)     at constructor.requireParams (/opt/cronicle/lib/api.js:474:23)     at constructor.api_create_event (/opt/cronicle/lib/api/event.js:84:13)     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)     at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:1108:12)     at /opt/cronicle/node_modules/pixl-server-web/web_server.js:1041:10     at /opt/cronicle/node_modules/async/dist/async.js:473:16     at replenish (/opt/cronicle/node_modules/async/dist/async.js:993:25)     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)     at /opt/cronicle/node_modules/async/dist/async.js:958:16]
[1602168417.875][2020-10-08 16:46:57][Server082][2193126][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read property 'toString' of null][]
[1602169190.88][2020-10-08 16:59:50][Server082][2500886][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'toString' of null][TypeError: Cannot read property 'toString' of null     at constructor.requireParams (/opt/cronicle/node_modules/pixl-server-user/user.js:1298:21)     at constructor.requireParams (/opt/cronicle/lib/api.js:474:23)     at constructor.api_create_event (/opt/cronicle/lib/api/event.js:84:13)     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)     at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:1108:12)     at /opt/cronicle/node_modules/pixl-server-web/web_server.js:1041:10     at /opt/cronicle/node_modules/async/dist/async.js:473:16     at replenish (/opt/cronicle/node_modules/async/dist/async.js:993:25)     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)     at /opt/cronicle/node_modules/async/dist/async.js:958:16]
[1602169190.886][2020-10-08 16:59:50][Server082][2500886][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read property 'toString' of null][]
[1602170781.575][2020-10-08 17:26:21][Server082][698][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'toString' of null][TypeError: Cannot read property 'toString' of null     at constructor.requireParams (/opt/cronicle/node_modules/pixl-server-user/user.js:1298:21)     at constructor.requireParams (/opt/cronicle/lib/api.js:474:23)     at constructor.api_create_event (/opt/cronicle/lib/api/event.js:84:13)     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)     at constructor.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/web_server.js:1108:12)     at /opt/cronicle/node_modules/pixl-server-web/web_server.js:1041:10     at /opt/cronicle/node_modules/async/dist/async.js:473:16     at replenish (/opt/cronicle/node_modules/async/dist/async.js:993:25)     at iterateeCallback (/opt/cronicle/node_modules/async/dist/async.js:983:17)     at /opt/cronicle/node_modules/async/dist/async.js:958:16]
[1602170781.583][2020-10-08 17:26:21][Server082][698][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read property 'toString' of null][]

**Comment by jhuckaby** [comment] 2020-10-08 17:03
Thank you for this crash report.  I'll look into this tonight.

**Comment by jhuckaby** [comment] 2020-10-09 01:09
Okay, so @Taz4Git, somehow your Cronicle schedule data has something really weird in it.  One of the parameters in your event you are trying to copy is `null` which is crashing the server.  This property is required to be a string, so it is really bizarre how it became `null`.  I can't tell which property it was from the crash log.

I have added protection against this particular crash, and pushed a new version of the [helper library](https://github.com/jhuckaby/pixl-server-user/commit/c2b6b2ae745654983015b098e7d9f2890589a664) (instructions below for updating), but the fact remains, something bizarre is going on with your schedule data -- specifically, this one event you are trying to copy.

Did you originally create the event with the API perchance?  That might explain it.

Would it be possible for you to send me (privately) your raw schedule JSON data, so I can examine the event and see which property is set to `null`?

If so, please run these commands and send me the output at `jhuckaby AT gmail DOT com`:

```
cd /opt/cronicle
bin/storage-cli.js list_get global/schedule
```

And then please tell me which event you were trying to copy (the event title or ID would be fine).

Here are the instructions to upgrade the helper library, which will prevent the crash in the future, but it won't be able to successfully copy your event until we figure out where the `null` property is coming from.

```
cd /opt/cronicle
bin/control.sh stop
npm install
bin/control.sh start
```

Thanks!

**Comment by mikeTWC1984** [comment] 2020-10-09 02:34
Was playing with 0.8.49 updates for a few days, cannot reproduce this error

**Comment by Taz4Git** [comment] 2020-10-09 08:16
I have to change my answer after further testing. (did not patch helper library yet)

Can you reproduce the crash consistently?
Yes BUT only with a specific user and the server also crashes when creating a new event.

Privileges of the user when cronicle crashes:
- Create Events
- Edit Events
- Delete Events
- Run Events
- Abort Events
- Toggle Scheduler

When an Administrator copies or creates an event, it works without problems.

**Comment by mikeTWC1984** [comment] 2020-10-09 14:40
OK, I can reproduce it now. Looks like that because non-admin user can't select target server when creating a job

**Comment by mikeTWC1984** [comment] 2020-10-09 14:56
If you limit user with some (or all) server group  then it shouldn't  crash

Some other observation regarding group limitation feature:
- "All servers" is treated as distinct group. E.g. job is assigned to "master group" and user to "all servers". User won't see that job
-  On completed job list - user can see jobs from groups he is not assigned to, but won't be able to see details anyway. Would be more logical to hide those jobs from the list  (it works this way when viewing future scheduled jobs on the main page)

**Comment by jhuckaby** [comment] 2020-10-09 16:52
Ah, I see the problem, thanks @mikeTWC1984 and @Taz4Git.  Working on this now...

**Closed** 2020-10-09 17:02 UTC
Labels: bug, need info

**Comment by jhuckaby** [comment] 2020-10-09 17:03
Fixed in [v0.8.50](https://github.com/jhuckaby/Cronicle/releases/tag/v0.8.50).  Thank you both for all the detailed information!

@mikeTWC1984 I will address your other concerns in a later release.  Fixing those things is more involved, and I don't have the time at the moment.  I will create new issues out of them tho, so we don't lose them.  Thanks!

**Comment by Taz4Git** [comment] 2020-10-09 18:19
Thanks for the quick response and fix!

**Comment by Taz4Git** [comment] 2020-10-12 13:41
> Thanks for the quick response and fix!

Updated cronicle, set user back to normal and it still works 👍
