### ISSUE TITLE
Cronicle Crash

### ISSUE THREAD

**Issue by pallavibatra-cpi** [jhuckaby/Cronicle#25] opened 2017-04-28 11:16 UTC
Hey Joseph, 
I was using delete_event api to delete event and as soon as i use it, the cronicle crashes. The event that was deleted was supposed to run every 5 minutes.
Please find below the crash.log file : 

Fri Apr 28 2017 15:31:00 GMT+0530 (IST)
TypeError: Cannot read property 'minutes' of undefined
    at constructor.checkEventTimingMoment (/opt/cronicle/lib/scheduler.js:200:13)
    at /opt/cronicle/lib/scheduler.js:107:17
    at /opt/cronicle/node_modules/async/lib/async.js:1213:16
    at /opt/cronicle/node_modules/async/lib/async.js:166:37
    at Object.async.whilst (/opt/cronicle/node_modules/async/lib/async.js:792:13)
    at /opt/cronicle/lib/scheduler.js:99:12
    at /opt/cronicle/node_modules/async/lib/async.js:1213:16
    at /opt/cronicle/node_modules/async/lib/async.js:166:37
    at /opt/cronicle/node_modules/async/lib/async.js:181:20
    at iterate (/opt/cronicle/node_modules/async/lib/async.js:262:13)
Please help me with this crash.

And after deleted the event when i restart the cronicle, in the COMPLETED tab, i can see all the job ids but "(None)' in Event Name.  Below is the screenshot : 
![image](https://cloud.githubusercontent.com/assets/25767871/25526067/86552e02-2c2f-11e7-90a8-1ea2e97bd8cc.png)

Is there any way possible to show the name of the event it was running before it got deleted.

Thanks
Pallavi
(pallavi.batra@chargepoint.com)

**Comment by jhuckaby** [comment] 2017-04-29 16:33
Hello @pallavibatra-cpi,

Thank you for this bug report.  However, in order for me to be able to fix it, I need more information from you.  You see, I delete items from the schedule all the time, and I have never had a crash.  Also, the point in the code where the crash occurred is very strange.  I think there may be some invalid data in your schedule.  Specifically, I think one of the events in your schedule is missing its `timing` property.

First, would it be possible for you to tell me more about your setup?  Specifically:

- What OS / version you are running on (CentOS 7, Ubuntu, OS X, etc.)
- What Cronicle version do you have (see bottom-right corner of web interface)?
- Are you using a multi-server setup, or just a single server?
- Are you using the filesystem as the back-end storage, or S3/Couchbase?
- Can you reproduce the crash consistently?

Also, can you send me a copy of your raw schedule data?  Assuming it doesn't contain any of your company secrets (feel free to black those out):

```sh
sudo /opt/cronicle/bin/storage-cli.js list_get global/schedule
```

What I am trying to determine here is if we're dealing with some kind of race condition, or other issue.  You say that you are calling the `delete_event` API.  Is it possible you are calling this API at the exact moment the event is trying to run?  Or sometime before?

What other Cronicle APIs are you using, if I may ask?  `create_event` or `update_event` perhaps?  What I am getting at is, my nose tells me this smells like some "bad data" is in your schedule, perhaps an event without a `timing` object.  Is it possible you created an event without a `timing` object?  This isn't possible using the Web UI, but it is possible if you use the `create_event` or `update_event` APIs.  The APIs don't explicitly require that property, but it is definitely required (I will fix that).

Thank you for any additional information you can provide me about this issue.

\- Joe

**Comment by jhuckaby** [comment] 2017-04-29 23:14
FYI, I just released Cronicle [v0.6.14](https://github.com/jhuckaby/Cronicle/releases/tag/v0.6.14) which has much more strict validation of the event data when calling the API.  If my hunch is correct and this issue is caused by bad data (e.g. missing `timing` object) when calling the `create_event`, `update_event` or `run_event` APIs, then this should fix it.

The scheduler will also now silently skip over events that are missing a `timing` object rather than crashing, to prevent crashes on pre-existing bad data created on the previous release.

Please let me know if this is still an issue after upgrading.

**Comment by pallavibatra-cpi** [comment] 2017-05-02 16:28
That's great Joseph. Though i will try to test it on the updated version but just to give you more details this is what i ws trying to do :
Step 1. Get all the events using get_schedule api.
Step 2. Change some values, like category,target of some events from get_schedule list.
Step 3. Use create/update_event to update the values and use delete_event api to delete some of the events.

I guess the problem is with the create event, as when i am calling it, it creates an event with code : 0 but the cronicle crashes.
Below is the array that i am trying to pass as an array to curl POSTFILEDS
(

    [enabled] => 1

    [params] => Array

        (

    [script] => #!/bin/sh

            # Enter your shell script code here
            echo " hello"
        )

    [timing] => Array
        (
            [minutes] => Array
                (
                    [0] => 0
                    [1] => 5
                    [2] => 10
                    [3] => 15
                    [4] => 20
                    [5] => 25
                    [6] => 30
                    [7] => 35
                    [8] => 40
                    [9] => 45
                    [10] => 50
                    [11] => 55
                )

        )

    [max_children] => 1
    [timeout] => 3600
    [catch_up] => 0
    [timezone] => Asia/Kolkata
    [plugin] => shellplug
    [title] => test1
    [category] => general
    [target] => maingrp
    [algo] => round_robin
    [multiplex] => 0
    [stagger] => 0
    [retries] => 0
    [retry_delay] => 0
    [detached] => 0
    [chain] => 
    [notify_success] => qa-cronicle-job-success@chargepoint.com
    [notify_fail] => qa-cronicle-job-fail@chargepoint.com
    [web_hook] => 
    [cpu_limit] => 0
    [cpu_sustain] => 0
    [memory_limit] => 0
    [memory_sustain] => 0
    [notes] => 
    [id] => ej278ui1a11
    [api_key] => 9cc7f96ea087d551f64006cab5c49c88
)

**Comment by jhuckaby** [comment] 2017-05-03 02:19
Hmm, I'd have to see the actual JSON to see what is really going on.  Try the new version and see I guess.

Also, can you send me a copy of your raw schedule data? Assuming it doesn't contain any of your company secrets (feel free to black those out):

```
sudo /opt/cronicle/bin/storage-cli.js list_get global/schedule
```

**Comment by pallavibatra-cpi** [comment] 2017-05-03 07:27
Before upgrading, the result of this command : sudo /opt/cronicle/bin/storage-cli.js list_get global/schedule is : [global.txt](https://github.com/jhuckaby/Cronicle/files/972656/global.txt)
I upgraded the cronicle and now i am not able to create an event.
Error code is 
`    {
        "code":"api",
       "description":"Malformed parameter type: catch_up (string)"
    }`

**Comment by jhuckaby** [comment] 2017-05-04 02:29
Ah ha, so my theory was right.  Your schedule has some malformed data in it, specifically this stuff here, in your `etl_driver_rfid_modify_cards` event:

```
"params[script]": "#!/bin/bash\n\n# Enter your shell script code here\nbash /home/deployer/etl/scripts/run-etl.sh driver_rifd_cards Detailed true\n",
"timing[hours][0]": "2",
"timing[minutes][0]": "20",
```

Somehow your code that composes the object into JSON to post to the API got really confused, and created all these weird JSON keys with actual literal array indexes in them: `timing[hours][0]`, `timing[minutes][0]` and so on.  This isn't good at all.

This is why Cronicle was crashing.  It has no idea how to interpret this.  There is no `timing` object, and there are a bunch of other problems with the data as well.

So the real problem here is that the API wasn't performing strict validation of the event data.  It did some light validation of some main params, but then it essentially let anything get through.  That's been fixed now, so now you are seeing what the API *should* have returned originally:

```
{ "code":"api", "description":"Malformed parameter type: catch_up (string)" }
```

So now you're going to have to be very careful composing your API requests, and make sure the parameters are all well-formed, and adhere to the documentation.  In this particular error, your `catch_up` parameter is coming in as a **string**, when it needs to be a Boolean (or 0 or 1).  This is what your script is sending:

```
"catch_up": "0",
```

No quotes are allowed in this parameter value -- it needs to be literal `true`, `false`, `0` or `1`.  So maybe change it to this:

```
"catch_up": 0,
```

But that is only one of the problems.  If you look at your event data in the file you sent over, there are lots and lots of issues.  This is just one of them.  But at least the API will now correctly error out, and tell you what is wrong, so you can fix it.

You should also delete the `etl_driver_rfid_modify_cards` event (Event ID: `e******0z`), because it is *very very* malformed, and will probably cause other crashes if left in there.

Good luck!

**Comment by pallavibatra-cpi** [comment] 2017-05-04 07:46
Yeah you were right Joseph. That error has been corrected from our side now. Thanks for that. But can you please look into the second issue that i have mentioned.

I am not able to see the event name in COMPLETE tab once i delete that event. It is because of the same "malformed data" or am i missing something else.

Thanks again
Pallavi

**Comment by jhuckaby** [comment] 2017-05-04 17:30
The event name bug is a separate issue, so I created a new ticket for it: https://github.com/jhuckaby/Cronicle/issues/28

I'll see what I can do about #28.  Closing #25 for now tho.

**Closed by jhuckaby** 2017-05-04 17:30 UTC
