### ISSUE TITLE
How to give parameters in cronicle?

### ISSUE THREAD

**Issue by hiba007** [jhuckaby/Cronicle#165] opened 2019-03-19 11:28 UTC
## Summary

I am facing issue how to use parameters. what are roles of parameters.Why we use it?

## Steps to reproduce the problem

1) I go to Admin tab
2) I write plugin name : Python Script
3) I write executable path : /usr/bin/python /home/rehman/PycharmProjects/queries/stats.py path
4) Then I go add parameters
5) I give parameter id : path
          label:path
          Default Value : '/home/rehman/PycharmProjects/queries'
6) I get error NameError: name 'path' is not defined

## Your Setup
locahost

### Operating system and version?

Ubuntu 18.04

### Node.js version?

v8.10.0

### Cronicle software version?

Version 0.8.28

### Are you using a multi-server setup, or just a single server?

single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?

back-end storage

### Can you reproduce the crash consistently?

yes

## Log Excerpts

Traceback (most recent call last):
  File "/home/rehman/PycharmProjects/queries/stats.py", line 106, in <module>
    conf_file = path+'/info.config'
NameError: name 'path' is not defined

Job failed at 2019/03/19 16:27:58 (GMT+5).
 Error: Child 13852 crashed with code: 1
 End of log.

**Comment by jhuckaby** [comment] 2019-03-19 23:19
Parameters are passed into your script as properties of a JSON object which is serialized and sent to your script's STDIN pipe.  If you want to make use of them, you have to "read" the JSON from STDIN and parse it.  Then you can find your parameters in an object named `params`.  This is described in the section [Writing Plugins](https://github.com/jhuckaby/Cronicle#writing-plugins) in the docs.  I am not sure how to do this in Python, but there are examples provided in [Perl](https://github.com/jhuckaby/Cronicle#sample-perl-plugin), [PHP](https://github.com/jhuckaby/Cronicle#sample-php-plugin) and [Node.js](https://github.com/jhuckaby/Cronicle#sample-node-plugin).

Alternatively, parameters are also passed to your script as environment variables, converted to upper-case.  For more details on this, see the [Job Environment Variables](https://github.com/jhuckaby/Cronicle#job-environment-variables) section in the docs.

Good luck.  I am closing this issue because it is not a bug.

**Closed by jhuckaby** 2019-03-19 23:19 UTC

**Comment by hiba007** [comment] 2019-03-20 06:36
In Python

import json,sys

path = json.load(sys.stdin)["params"]["path"]

Cronicle takes json as input

Got it!
