### ISSUE TITLE
Cronicle slave crashes when trying to add it to master with Uncaught Exception (TypeError)

### ISSUE THREAD

**Issue by mpatel-cpi** [jhuckaby/Cronicle#164] opened 2019-03-14 20:22 UTC
## Summary

I tried to add a slave to master and the slave crashes with Uncaught Exception (TypeError)

## Steps to reproduce the problem

1. Created a new Cronicle master (verified its working fine)
2. Configured a Cronicle Slave
3. On master's WebUI tried adding the slave server and got "Error: Failed to contact server: Error: socket hang up". Found crash details in Cronicle.log on the slave (see below).

## Your Setup

1 master + 1 slave (both running same version of OS, Node, Cronicle)

### Operating system and version?

Ubuntu 18.04.2 LTS

### Node.js version?

v10.15.3

### Cronicle software version?

Cronicle v0.8.28

### Are you using a multi-server setup, or just a single server?
1 master + 1 slave

### Are you using the filesystem as back-end storage, or S3/Couchbase?
Filesystem

### Can you reproduce the crash consistently?
Yes

## Log Excerpts

```
[1552590351.12][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][2][Spawning background daemon process (PID 32370 will exit)][["/usr/bin/node","/home/deployer/cronicle/lib/main.js"]]
[1552590351.478][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][1][Cronicle v0.8.28 Starting Up][{"pid":32377,"ppid":1,"node":"v10.15.3","arch":"x64","platform":"linux","argv":["/usr/bin/node","/home/deployer/cronicle/lib/main.js"],"execArgv":[]}]
[1552590351.481][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][9][Writing PID File: logs/cronicled.pid: 32377][]
[1552590351.482][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][9][Confirmed PID File contents: logs/cronicled.pid: 32377][]
[1552590351.483][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][2][Server IP: 172.23.65.56, Daemon PID: 32377][]
[1552590351.484][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][3][Starting component: Storage][]
[1552590351.487][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][3][Starting component: WebServer][]
[1552590351.501][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][3][Starting component: API][]
[1552590351.502][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][3][Starting component: User][]
[1552590351.502][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][3][Starting component: Cronicle][]
[1552590351.503][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][3][Cronicle engine starting up][]
[1552590351.508][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][4][Using broadcast IP: 172.23.67.255][]
[1552590351.508][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][4][Starting UDP server on port: 3014][]
[1552590351.513][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][4][Server not found in cluster -- waiting for a master server to contact us][]
[1552590351.513][2019-03-14 19:05:51][jobserver.local][Cronicle][debug][2][Startup complete, entering main loop][]
[1552591066.046][2019-03-14 19:17:46][jobserver.local][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read property 'perf' of undefined][TypeError: Cannot read property 'perf' of undefined     at constructor.sendHTTPResponse (/home/deployer/cronicle/node_modules/pixl-server-web/web_server.js:1047:17)     at Server.handler (/home/deployer/cronicle/node_modules/pixl-server-web/web_server.js:169:10)     at Server.<anonymous> (/home/deployer/cronicle/node_modules/engine.io/lib/server.js:470:22)     at Server.<anonymous> (/home/deployer/cronicle/node_modules/socket.io/lib/index.js:343:16)     at Server.emit (events.js:189:13)     at parserOnIncoming (_http_server.js:676:12)     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)]
[1552591066.047][2019-03-14 19:17:46][jobserver.local][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read property 'perf' of undefined][]
[1552591112.211][2019-03-14 19:18:32][jobserver.local][Cronicle][debug][2][Spawning background daemon process (PID 2053 will exit)][["/usr/bin/node","/home/deployer/cronicle/lib/main.js"]]
```

**Comment by jhuckaby** [comment] 2019-03-15 16:28
From the stack trace it looks like you are using HTTPS, and specifically `https_force`.  These are not supported in Cronicle.  HTTPS support is on the long-term TODO list, but I haven't even begun to address all the various issues that will arise with it.

However, this specific crash is technically a bug in my web server module, [pixl-server-web](https://github.com/jhuckaby/pixl-server-web), so I will go ahead and fix that, and you can manually upgrade it in your Cronicle installation, but I have to advise extreme caution here.  Using HTTPS and specifically `https_force` will not work as designed in Cronicle, and will probably cause a ton of other issues, crashes, pain and suffering.

**Comment by jhuckaby** [comment] 2019-03-15 17:00
Okay, this specific crash has been fixed in [pixl-server-web v1.1.15](https://github.com/jhuckaby/pixl-server-web/commit/32b75e7f5c9a78b1a15beb16903ea720232d49a4), but I have to say, just to be clear, HTTPS and specifically `https_force` are **not going to work in Cronicle**.  Proper HTTPS support is a long way off, I am afraid.  I apologize for this, but thank you for the bug report.

For what it's worth, you can force an upgrade of the pixl-server-web module like this:

```sh
cd /opt/cronicle
sudo bin/control.sh stop
sudo npm install pixl-server-web
sudo bin/control.sh start
```

**Closed by jhuckaby** 2019-03-15 17:00 UTC

**Comment by mpatel-cpi** [comment] 2019-03-15 17:23
Thanks for your quick and helpful response (as usual). I upgraded the `pixl-server-web` component, turned off `https_force` and confirm that slave was added to Cronicle successfully. 

You've built an amazing product. Hopefully you get more usage and resources to help you keep making it awesomer :)

**Comment by jhuckaby** [comment] 2019-03-15 18:34
Thanks man!  That is much appreciated.  I've been so busy with other projects that Cronicle has taken a back seat, but I am looking forward to getting back into it again :)
