### ISSUE TITLE
No master server found [Waiting for master server...]

### ISSUE THREAD

**Issue by prajasunil17** [jhuckaby/Cronicle#561] opened 2022-12-16 05:40 UTC
We checked same all step all configuration is perfect please find below output .

[root@ip-10-0-0-123 cronicle]# **hostname**
**apps.cms.com**
[root@ip-10-0-0-123 cronicle]# **bin/storage-cli.js list_get global/server_groups**
Got 2 items.
**Items from list: global/server_groups: [
	{
		&quot;id&quot;: &quot;maingrp&quot;,
		&quot;title&quot;: &quot;Primary Group&quot;,
		&quot;regexp&quot;: &quot;^(apps\\.cms\\.com)$&quot;,
		&quot;master&quot;: 1
	},
	{
		&quot;id&quot;: &quot;allgrp&quot;,
		&quot;title&quot;: &quot;All Servers&quot;,
		&quot;regexp&quot;: &quot;.+&quot;,
		&quot;master&quot;: 0
	}
]**

[root@ip-10-0-0-123 cronicle]# **bin/storage-cli.js list_get global/servers**
Got 1 items.
**Items from list: global/servers: [
	{
		&quot;hostname&quot;: &quot;apps.cms.com&quot;,
		&quot;ip&quot;: &quot;10.0.25.124&quot;
	}
]**

In **Cronicle.log**  capture log.

![image](https://user-images.githubusercontent.com/69504834/207849219-fb372da6-fba1-4253-a57b-9bbe1043d5c1.png)

But still getting same error. No idea what is a wrong.
Can me suggest me how can solve this issue.

_Originally posted by @prajasunil17 in https://github.com/jhuckaby/Cronicle/issues/560#issuecomment-1352663729_

**Comment by jhuckaby** [comment] 2022-12-16 05:43
This is a duplicate of #560.  Closing it.

**Closed by jhuckaby** 2022-12-16 05:43 UTC
Labels: duplicate
